### ISSUE TITLE
Masking Sentence

### ISSUE THREAD

**Issue by Seunggu0305** [Jazzcharles/OVSegmentor#1]
How did you masked sentece's entities when using clip text encoder's pre-trained weight?

**Comment by Jazzcharles** [comment]
CLIP text encoder is not trained with masked input, and it is encouraged to replace the masked word with special tokens. We choose a single character 'M' as the masked token as it does not mean anything in the sentence. We did not use '[MASK]' as  BPE tokeniser tended to separate it into multiple tokens.

**Comment by Seunggu0305** [comment]
https://github.com/Jazzcharles/OVSegmentor/blob/27e28837025238bc94baec377a6df5158715a03f/datasets/tokenizer.py#L159 in this line there are still ".lower()" remains, How did you except the capital letter 'M'?

**Comment by Seunggu0305** [comment]
Is the class designed to appear only once in a batch?

**Comment by Seunggu0305** [comment]
Is the class designed to appear only once in a batch?

**Comment by Jazzcharles** [comment]
We simply replaced the masked word with the bpe_token of 'M'.  Please refer to Line359 in clip_dataset.py. I think using 'm' as the masked word also works. 

> https://github.com/Jazzcharles/OVSegmentor/blob/27e28837025238bc94baec377a6df5158715a03f/datasets/tokenizer.py#L159
> 
> in this line there are still ".lower()" remains, How did you except the capital letter 'M'?

**Comment by Jazzcharles** [comment]
> Is the class designed to appear only once in a batch?

No, we did not enforce this during training. If only ONE entitiy is masked in the caption, perhaps there will be false positive pairs in the contrastive learning.

**Comment by Seunggu0305** [comment]
How did you extract [EOT] token features from features in losses?

**Comment by Jazzcharles** [comment]
> How did you extract [EOT] token features from features in losses?

https://github.com/Jazzcharles/OVSegmentor/blob/main/models/transformer.py#L315
