### ISSUE TITLE
How long will the two stages of training this model take？

### ISSUE THREAD

**Issue by canbaoburen** [Jazzcharles/OVSegmentor#7]
Thank you for your great work and code! 
I wonder how long will the two stages of training this model take. 
Thanks!

**Comment by Jazzcharles** [comment]
Hi, It takes around 30 mins for stage-1 training on 16A100 80G gpus, and 1.5 hours for stage-2 training on 8 A100 80G gpus.
We only use 8 gpus for stage-2 training due to the lack of enough gpus back that time.
